### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wrist** [wrist/streamlit-dsp#1]
## general TODOs

* [x] add a static page to select to load which applications
* [x] add axis labels to charts
* [x] add license
* [ ] add tests
* [ ] add CI/CD using GitHub actions
* [ ] publish to PyPI if needed
* [x] run apps on somewhere online under jupyterhub
    * Now run on Heroku(of course without jupyterhub)
* [ ] investigate how to persist the application state
* [x] write a blog article and slide to give a presentation(in Japanese)

## `window_viewer.py`

* [x] add additional parameters GUI to all filters require them
* [x] specify sidelobe decibel instead of beta parameter for kaiser window
* [ ] handle whether a window is a symmetry or not
* [x] implement code generator
* [x] enable to use multiselect

## `filter-designer.py`

* [ ] implement FIR filter designer
* [ ] implement IIR filter designer
* [x] implement code generator

## `room_designer.py`

* [x] enable to treat multiple input sound files in `room_designer.py`
* [x] investigate the reason a room 3D plot is widened outside of axis when `img_order` is greater than 0
     * this behavor can be avoided by executing `room.plot(img_order=0)` or to set xlim/ylim/zlim to room ax
* [x] implement code generator
